#!/usr/bin/env python3

import sys

from rqt_balancer.my_module import MainWindow
from rqt_gui.main import Main

plugin = 'rqt_balancer'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
