#!/usr/bin/env python3

import sys

from rqt_gui.main import Main

from rqt_balancer.my_module import MainWindow


plugin = 'rqt_balancer'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
